# metadata -- add as many key/value pairs as you want
[metadata]
org = "DNT"
maintainer = "Roar Skår  & Sami Alajrami (sami@praqma.com)"

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
[certificates]
caCrt    = "$DEV_CLUSTER_CERT"
caKey    = "$DEV_CLUSTER_CLIENT_KEY"
caClient = "$DEV_CLUSTER_CLIENT_CERT"

[settings]
kubeContext = "dnt" # will try connect to this context first, if it does not exist, it will be created using the details below
username = "admin"
password = "$DEV_CLUSTER_PASSWORD" # admin user password
clusterURI = "$DEV_CLUSTER_URI" # cluster API
slackWebhook = "$SLACK_WEBHOOK_HELMSMAN"



# define your environments and thier k8s namespaces
# syntax: (whitespaces don't matter)
# [namespaces]
# [namespaces.<your namespace>]
#  protected = <true/false> # default is false
[namespaces]
[namespaces.beta]

# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
[helmRepos]
dnt = "gs://dnt-helm-repo"

# define the desired state of your applications helm charts
# each contains the following:

[apps]

[apps.geoserver]
    name = "geoserver-beta" # should be unique across all apps
    description = "Geoserver beta app."
    namespace = "beta" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "dnt/web-app" # changing the chart name means delete and recreate this chart
    version = "0.7.0" 
    valuesFile = "geoserver-beta-values.yaml"
    protected = true
    [apps.geoserver.set]
       "containers[0].environment.LIBRATO_TOKEN" = "$GEOSERVER_LIBRATO_TOKEN"
       "containers[0].environment.MONGO_URI" = "$GEOSERVER_MONGO_URI"
       "containers[0].environment.SENTRY_DNS" = "$GEOSERVER_SENTRY_DNS"
